services:
  query_postgres:
    image: postgres:12-alpine
    restart: ${RESTART_POLICY:-always}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    shm_size: ${POSTGRES_SHM_SIZE}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - common_net

  query:
    image: ghcr.io/openfoodfacts/openfoodfacts-query:${TAG}
    restart: ${RESTART_POLICY:-always}
    environment:
      - POSTGRES_HOST=query_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MONGO_URI
      - REDIS_URL
      - LOG_LEVEL
    # Use a different number so does not clash with locally running instance
    ports:
      - "${QUERY_PORT:-5511}:5510"
    depends_on:
      query_postgres:
        condition: service_started
    networks:
      - common_net

networks:
  common_net:
    name: ${COMMON_NET_NAME}
    external: true

volumes:
  dbdata:
