services:
  query_postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - po_default

  query:
    image: ghcr.io/openfoodfacts/openfoodfacts-query:${TAG}
    environment:
      - POSTGRES_HOST=query_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MONGO_URI
    networks:
      - po_default
    depends_on:
      query_postgres:
        condition: service_started

networks:
  po_default:
    external: true
    name: po_default

volumes:
  dbdata:
