x-query-conf: &query-conf
  image: ghcr.io/openfoodfacts/openfoodfacts-query/query:${TAG}
  environment:
    - POSTGRES_HOST
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - MONGODB_HOST
  networks:
    - po_default

services:
  query:
    <<: *query-conf

networks:
  po_default:
    external: true
    name: po_default
