services:
  query_postgres:
    # Expose port locally for testing purposes.
    ports:
      - "${POSTGRES_PORT:-5512}:5432"
    volumes:
      - ./data:/mnt/data
    networks:
      - po_default

  query:
    build: .
    image: openfoodfacts-query:dev
    environment:
      # Use Product Opener's MongoDB
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./data:/data
    networks:
      - po_default

networks:
  po_default:
    external: true
    name: po_default
