services:
  query_postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=off
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ../data:/mnt/data
    networks:
      - po_default

  init:
    build: ../
    networks:
      - po_default
    depends_on:
      query_postgres:
        condition: service_started
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=query_postgres
    command: sh -cx "sleep 1 && npx mikro-orm migration:up"

  query:
    build: ../
    ports:
      - 5511:5510
    networks:
      - po_default
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=query_postgres
      - MONGODB_HOST=mongodb
    depends_on:
      init:
        condition: service_completed_successfully

volumes:
  dbdata:

networks:
  default:
  po_default:
    external: true
    name: po_default
