services:
  query_postgres:
    # Expose port locally for testing purposes.
    ports:
      - "${POSTGRES_EXPOSE:-5512}:5432"

  query:
    build: .
    image: openfoodfacts-query:dev
    environment:
      # Use shared-services MongoDB and REDIS
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379

    volumes:
      - ./data:/data
