name: Docker Compose Deployment

on:
  push:
    branches:
      - 'main'
      - deploy-*
    tags:
      - v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          # FIXME name you envs, see reuse below
          # it's also the name of the directory for the application
          - ${{ startsWith(github.ref, 'refs/tags/v') && 'off-query-org' || 'off-query-net' }}
    environment: ${{ matrix.env }}
    concurrency: ${{ matrix.env }}
    steps:
      - name: Set common variables
        run: |
          echo "SSH_PROXY_HOST=ovh1.openfoodfacts.org" >> $GITHUB_ENV
          echo "SSH_USERNAME=off" >> $GITHUB_ENV
      - name: Set various variable for staging deployment
        if: matrix.env == 'off-query-net'
        run: |
          # deploy target
          echo "SSH_HOST=10.1.0.200" >> $GITHUB_ENV
          # configurations
          echo "MONGO_URI=mongodb://10.1.0.200:27017" >> $GITHUB_ENV
      - name: Set various variable for production deployment
        if: matrix.env == 'off-query-org'
        run: |
          # deploy target
          echo "SSH_HOST=10.1.0.201" >> $GITHUB_ENV
          # configurations
          echo "MONGO_URI=mongodb://213.36.253.195:27017" >> $GITHUB_ENV

      - name: Wait for container build workflow
        uses: tomchv/wait-my-workflow@v1.1.0
        id: wait-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 10
          timeoutSeconds: 600 # 10m

      - name: Do something if build isn't launched
        if: steps.wait-build.outputs.conclusion == 'not found'
        run: echo job does not exist && true

      - name: Do something if build fail
        if: steps.wait-build.outputs.conclusion == 'failure'
        run: echo fail && false # fail if build fail

      - name: Do something if build timeout
        if: steps.wait-build.outputs.conclusion == 'timed_out'
        run: echo Timeout && false # fail if build time out

      - name: Checkout git repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            # Clone Git repository if not already there
            [ ! -d '${{ matrix.env }}' ] && git clone --depth 1 https://github.com/${{ github.repository }} ${{ matrix.env }} --no-single-branch 2>&1

            # Go to repository directory
            cd ${{ matrix.env }}

            # Fetch newest commits (in case it wasn't freshly cloned)
            git fetch --depth 1

            # Checkout current commit SHA
            git checkout -qf ${{ github.sha }}

      - name: Set environment variables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            # Go to repository directory
            cd ${{ matrix.env }}

            # new env
            rm .env
            touch .env
            # Set Docker Compose variables
            echo "DOCKER_CLIENT_TIMEOUT=120" >> .env
            echo "COMPOSE_HTTP_TIMEOUT=120" >> .env
            echo "COMPOSE_PROJECT_NAME=off-query" >> .env
            echo "COMPOSE_PATH_SEPARATOR=;" >> .env
            echo "COMPOSE_FILE=docker-compose.yml" >> .env
            echo "TAG=sha-${{ github.sha }}" >> .env

            # App environment variables
            echo "POSTGRES_USER=postgres" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=query" >> .env
            echo "MONGO_URI=${{ env.MONGO_URI }}" >> .env

      # Not worried about this at the moment as data is a cache

      # - name: Create external Docker volumes
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ env.SSH_HOST }}
      #     username: ${{ env.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     proxy_host: ${{ env.SSH_PROXY_HOST }}
      #     proxy_username: ${{ env.SSH_USERNAME }}
      #     proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script_stop: false
      #     script: |
      #       cd ${{ matrix.env }}
      #       docker volume create <VOLUME_NAME>

      - name: Start services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            cd ${{ matrix.env }}
            docker-compose up -d 2>&1

      - name: Check services are up
        uses: appleboy/ssh-action@master
        if: ${{ always() }}
        id: livecheck
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            cd ${{ matrix.env }}
            exit_code=0
            for service in `docker-compose config  --service | tr '\n' ' '`; do 
              if [ -z `docker-compose ps -q $service` ] || [ -z `docker ps -q --no-trunc | grep $(docker-compose ${{ env.compose_args }} ps -q $service)` ]; then
                echo "$service: DOWN"
                exit_code=1
              else
                echo "$service: UP"
              fi
            done;
            exit $exit_code;

      - name: Cleanup obsolete Docker objects
        uses: appleboy/ssh-action@master
        if: ${{ always() }}
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: false
          script: |
            cd ${{ matrix.env }}
            docker system prune -af
